# Generated by Django 3.2.8 on 2021-10-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicketApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_reservation',
            name='id_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
