# Generated by Django 3.2.8 on 2021-10-14 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicketApp', '0002_alter_tour_reservation_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_reservation',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='BookTicketApp.destination'),
        ),
    ]
