# Generated by Django 3.2.8 on 2021-10-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicketApp', '0003_tour_reservation_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_reservation',
            name='destination',
        ),
    ]
